trigger:
  paths:
    include:
      - result/**

variables:
  dockerRegistryServiceConnection: 'dockerhub'
  imageName: 'raool1/result'
  imageTag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build & Push Result Service
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      name: azureagent

    steps:
    - checkout: self

    - script: |
        cd result
        docker build -t $(imageName):$(imageTag) .
        docker tag $(imageName):$(imageTag) $(imageName):latest
      displayName: Build Docker image

    - task: Docker@2
      displayName: Push Docker image to Docker Hub
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        tags: |
          $(imageTag)
          latest
